name: Fasterstats
main: com.thefaster.bukkit.Fasterstats.Fasterstats
version: 0.1.0

commands:
  fasterstats:
    aliases: [fasterstats, fs]
    description: Provides access to Fasterstats commands and information.
    usage: |
           /<command>
           Example: /<command> | Displays Player statistic
           Example: /<command> time | Displays time played           
           Example: /<command> blocks | Displays blocks information
           Example: /<command> kills | Displays kills information
           Example: /<command> player <player name> | Displays other player info
           Example: /<command> player <player name> blocks | Displays other player blocks info
           Example: /<command> player <player name> kills | Displays other player kills info